services:
  rscore-data-provider-mock:
    build: .
    container_name: rscore_data_provider_mock
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - rscore-mock-network

networks:
  rscore-mock-network:
    name: rscore-mock-network
    driver: bridge